# La aplicación utiliza estos valores para abrir la instancia en MySQL en lugar de manipular directamente la clase dentro de los archivos, solo cambia los datos por los propios
db.url=jdbc:mysql://127.0.0.1:3307/tuticket?connectionTimeZone=LOCAL
db.user=root
db.password=root
