package presentacion;

public class FrmLogin extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger =
      java.util.logging.Logger.getLogger(FrmLogin.class.getName());

  private final negocio.ticketNegocio.ITicketNegocio negocio;

  public FrmLogin() {
    this(edu.mx.itson.ticketfanequipo8.TicketFanEquipo8.crearNegocio());
  }

  public FrmLogin(negocio.ticketNegocio.ITicketNegocio negocio) {
    initComponents();
    this.negocio = negocio;
    Tema.ventana(this, "Iniciar sesión");
    Tema.tarjeta(jPanel1);
    Tema.marca(jLabel1, "Vive tu próximo<br>gran momento.");
    jLabel2.setText(
        "<html><b style='font-size:22px'>Bienvenido de nuevo</b><br>Ingresa a tu cuenta</html>");
    Tema.campo(jTextField1, "Usuario");
    Tema.campo(jPasswordField1, "Contraseña");
    jButton1.setText("Iniciar sesión");
    jButton2.setText("Crear una cuenta");
    Tema.secundario(jButton2);
    jButton1.addActionListener(e -> Tema.ejecutar(this, this::ingresar));
    jPasswordField1.addActionListener(e -> Tema.ejecutar(this, this::ingresar));
    jTextField1.addActionListener(e -> jPasswordField1.requestFocusInWindow());
    jButton2.addActionListener(e -> Tema.abrir(this, new FrmRegistro(negocio)));
    getRootPane().setDefaultButton(jButton1);
  }

  private void ingresar() throws negocio.NegocioException {
    char[] clave = jPasswordField1.getPassword();
    try {
      dtos.UsuarioDTO sesion = negocio.iniciarSesion(jTextField1.getText(), clave);
      Navegacion.inicio(this, negocio, sesion);
    } finally {
      java.util.Arrays.fill(clave, '\0');
      jPasswordField1.setText("");
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Tema.instalarEstilo();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
