package presentacion;

public class FrmRegistro extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger =
      java.util.logging.Logger.getLogger(FrmRegistro.class.getName());

  private final negocio.ticketNegocio.ITicketNegocio negocio;

  public FrmRegistro() {
    this(edu.mx.itson.ticketfanequipo8.TicketFanEquipo8.crearNegocio());
  }

  public FrmRegistro(negocio.ticketNegocio.ITicketNegocio negocio) {
    initComponents();
    this.negocio = negocio;
    Tema.ventana(this, "Crear cuenta");
    Tema.tarjeta(jPanel1);
    Tema.marca(jLabel1, "Comienza tu<br>próxima experiencia.");
    jLabel2.setText(
        "<html><b style='font-size:19px'>Crea tu cuenta</b> · 3 cuentas de $1,000 MXN</html>");
    Tema.campo(jTextField1, "Nombres");
    Tema.campo(jTextField2, "Apellido paterno");
    Tema.campo(jTextField3, "Apellido materno");
    jDateChooser1.setLocale(java.util.Locale.forLanguageTag("es-MX"));
    jDateChooser1.setDateFormatString("dd/MM/yyyy");
    jDateChooser1.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Fecha de nacimiento · calendario"));
    java.time.ZoneId zona = java.time.ZoneId.systemDefault();
    java.time.LocalDate hoy = java.time.LocalDate.now();
    jDateChooser1.setMinSelectableDate(
        java.util.Date.from(hoy.minusYears(120).atStartOfDay(zona).toInstant()));
    jDateChooser1.setMaxSelectableDate(java.util.Date.from(hoy.atStartOfDay(zona).toInstant()));
    ((javax.swing.JTextField) jDateChooser1.getDateEditor().getUiComponent()).setEditable(false);
    jDateChooser1.setDate(null);
    Tema.campo(jTextField5, "Usuario · 3 a 30 caracteres");
    Tema.campo(jPasswordField1, "Contraseña · mínimo 6 caracteres");
    jButton1.setText("Crear cuenta");
    jButton2.setText("Ya tengo cuenta · Iniciar sesión");
    Tema.secundario(jButton2);
    jButton1.addActionListener(e -> Tema.ejecutar(this, this::registrar));
    jButton2.addActionListener(e -> Tema.abrir(this, new FrmLogin(negocio)));
    pack();
    setLocationRelativeTo(null);
  }

  private void registrar() throws negocio.NegocioException {
    if (jDateChooser1.getDate() == null)
      throw new negocio.NegocioException("Selecciona tu fecha de nacimiento en el calendario.");
    java.time.LocalDate nacimiento =
        jDateChooser1.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
    char[] clave = jPasswordField1.getPassword();
    try {
      dtos.UsuarioDTO sesion =
          negocio.registrar(
              new dtos.CrearClienteDTO(
                  jTextField1.getText(),
                  jTextField2.getText(),
                  jTextField3.getText(),
                  nacimiento,
                  jTextField5.getText(),
                  clave));
      Tema.mensaje(
          this, "Tu perfil y tus tres cuentas están listos. Cada cuenta inicia con $1,000.00 MXN.");
      Navegacion.inicio(this, negocio, sesion);
    } finally {
      java.util.Arrays.fill(clave, '\0');
      jPasswordField1.setText("");
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jPanel1.setLayout(new java.awt.GridLayout(9, 0));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2);

        jTextField3.setText("jTextField3");
        jPanel1.add(jTextField3);
        jPanel1.add(jDateChooser1);

        jTextField5.setText("jTextField5");
        jPanel1.add(jTextField5);

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Tema.instalarEstilo();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRegistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
